# Generated by Django 5.0 on 2024-02-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_paid_order_paid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='usermame',
            new_name='username',
        ),
    ]
