# Generated by Django 5.0 on 2024-02-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='peyment_intent',
            new_name='payment_intent',
        ),
    ]
