# Generated by Django 4.2.8 on 2024-02-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_libraryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryitem',
            name='user',
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
